// Code generated by scripts/generate-eip712-registry.mjs. DO NOT EDIT.
import { MsgCancelAllOrders, MsgCancelOrder, MsgCreateMarket, MsgPlaceLimitOrder, MsgPlaceMarketOrder, MsgUpdateMarketParams } from "../proto/gen/ault/exchange/v1beta1/tx";
import { MsgApproveMember, MsgBatchApproveMember, MsgBatchMintLicense, MsgBatchRevokeMember, MsgBurnLicense, MsgMintLicense, MsgRevokeLicense, MsgRevokeMember, MsgSetKYCApprovers, MsgSetMinters, MsgSetTokenURI, MsgTransferLicense, MsgUpdateParams as MsgUpdateParamsAultLicenseV1 } from "../proto/gen/ault/license/v1/tx";
import { MsgBatchSubmitWork, MsgCancelMiningDelegation, MsgDelegateMining, MsgRedelegateMining, MsgRegisterOperator, MsgSetOwnerVrfKey, MsgSubmitWork, MsgUnregisterOperator, MsgUpdateOperatorInfo, MsgUpdateParams as MsgUpdateParamsAultMinerV1 } from "../proto/gen/ault/miner/v1/tx";
import { MsgWithdrawDelegatorReward } from "../proto/gen/cosmos/distribution/v1beta1/tx";
import { MsgBeginRedelegate, MsgDelegate, MsgUndelegate } from "../proto/gen/cosmos/staking/v1beta1/tx";
import { base64ToBytes } from "../core/base64";

const EMPTY_RECORD: Record<string, unknown> = {};

function asRecord(value: unknown): Record<string, unknown> {
  if (value && typeof value === "object" && !Array.isArray(value)) {
    return value as Record<string, unknown>;
  }
  return EMPTY_RECORD;
}

function getField(record: Record<string, unknown>, camel: string, snake: string): unknown {
  if (record[camel] !== undefined) {
    return record[camel];
  }
  return record[snake];
}

function requireString(value: unknown, label: string): string {
  if (typeof value !== "string") {
    throw new Error(`${label} must be a string.`);
  }
  return value;
}

function requireStringOrDefault(value: unknown, label: string, defaultValue = ""): string {
  if (value === undefined) {
    return defaultValue;
  }
  return requireString(value, label);
}

function requireBytes(value: unknown, label: string): Uint8Array {
  if (value instanceof Uint8Array) {
    return value;
  }
  if (typeof value === "string") {
    if (!/^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$/.test(value)) {
      throw new Error(`${label} must be a Uint8Array or valid base64 string.`);
    }
    return base64ToBytes(value);
  }
  throw new Error(`${label} must be a Uint8Array or base64 string.`);
}

function requireBool(value: unknown, label: string): boolean {
  if (typeof value !== "boolean") {
    throw new Error(`${label} must be a boolean.`);
  }
  return value;
}

function requireBoolOrDefault(value: unknown, label: string, defaultValue = false): boolean {
  if (value === undefined) {
    return defaultValue;
  }
  return requireBool(value, label);
}

function requireNumberLike(value: unknown, label: string): number {
  if (typeof value === "number" && Number.isFinite(value)) {
    return value;
  }
  if (typeof value === "bigint") {
    return Number(value);
  }
  if (typeof value === "string" && value.trim() !== "") {
    const parsed = Number(value);
    if (Number.isFinite(parsed)) {
      return parsed;
    }
  }
  throw new Error(`${label} must be a number.`);
}

function requireBigIntLike(value: unknown, label: string): bigint {
  if (typeof value === "bigint") {
    return value;
  }
  if (typeof value === "number" && Number.isFinite(value)) {
    if (!Number.isInteger(value)) {
      throw new Error(`${label} must be an integer.`);
    }
    if (!Number.isSafeInteger(value)) {
      throw new Error(`${label} exceeds safe integer range; use bigint or string.`);
    }
    return BigInt(value);
  }
  if (typeof value === "string" && value.trim() !== "") {
    return BigInt(value);
  }
  throw new Error(`${label} must be a bigint or decimal string.`);
}

function requireBigIntOrDefault(value: unknown, label: string, defaultValue = 0n): bigint {
  if (value === undefined) {
    return defaultValue;
  }
  return requireBigIntLike(value, label);
}

function requireInt32Like(value: unknown, label: string): number {
  const num = requireNumberLike(value, label);
  if (!Number.isInteger(num) || num < -2147483648 || num > 2147483647) {
    throw new Error(`${label} must be an int32.`);
  }
  return num;
}

function requireUint32Like(value: unknown, label: string): number {
  const num = requireNumberLike(value, label);
  if (!Number.isInteger(num) || num < 0 || num > 0xffffffff) {
    throw new Error(`${label} must be a uint32.`);
  }
  return num;
}

function requireUint32OrDefault(value: unknown, label: string, defaultValue = 0): number {
  if (value === undefined) {
    return defaultValue;
  }
  return requireUint32Like(value, label);
}

function requireArray<T>(value: unknown, label: string, mapper: (item: unknown, label: string) => T): T[] {
  if (!Array.isArray(value)) {
    throw new Error(`${label} must be an array.`);
  }
  return value.map((item, index) => mapper(item, `${label}[${index}]`));
}

function requireArrayOrDefault<T>(value: unknown, label: string, mapper: (item: unknown, label: string) => T, defaultValue: T[] = []): T[] {
  if (value === undefined) {
    return defaultValue;
  }
  return requireArray(value, label, mapper);
}

function requireStringArray(value: unknown, label: string): string[] {
  return requireArray(value, label, requireString);
}

function requireStringArrayOrDefault(value: unknown, label: string, defaultValue: string[] = []): string[] {
  return requireArrayOrDefault(value, label, requireString, defaultValue);
}

function requireBigIntArray(value: unknown, label: string): bigint[] {
  return requireArray(value, label, requireBigIntLike);
}

function requireRecordArray(value: unknown, label: string): Record<string, unknown>[] {
  if (!Array.isArray(value)) {
    throw new Error(`${label} must be an array of objects.`);
  }
  return value.map((item, index) => {
    if (!item || typeof item !== "object" || Array.isArray(item)) {
      throw new Error(`${label}[${index}] must be an object.`);
    }
    return item as Record<string, unknown>;
  });
}

function requireDuration(value: unknown, label: string): { seconds: bigint; nanos: number } {
  if (!value || typeof value !== "object" || Array.isArray(value)) {
    throw new Error(`${label} must be a protobuf Duration object.`);
  }
  const record = asRecord(value);
  if (record.seconds === undefined && record.nanos === undefined) {
    throw new Error(`${label} must include seconds or nanos.`);
  }
  const seconds = requireBigIntLike(record.seconds ?? 0n, `${label}.seconds`);
  const nanos = requireInt32Like(record.nanos ?? 0, `${label}.nanos`);
  if (nanos < -999999999 || nanos > 999999999) {
    throw new Error(`${label}.nanos must be between -999999999 and 999999999.`);
  }
  if (seconds > 0n && nanos < 0) {
    throw new Error(`${label}.nanos must be >= 0 when seconds is positive.`);
  }
  if (seconds < 0n && nanos > 0) {
    throw new Error(`${label}.nanos must be <= 0 when seconds is negative.`);
  }
  return { seconds, nanos };
}

function mapAultExchangeV1beta1MarketParamUpdate(input: unknown, label: string = "value") {
  const record = asRecord(input);
  const prefix = label ? `${label}.` : "";
  return {
    marketId: requireBigIntLike(getField(record, "marketId", "market_id"), `${prefix}marketId`),
    makerFeeRate: requireString(getField(record, "makerFeeRate", "maker_fee_rate"), `${prefix}makerFeeRate`),
    takerFeeRate: requireString(getField(record, "takerFeeRate", "taker_fee_rate"), `${prefix}takerFeeRate`),
  };
}

function mapAultExchangeV1beta1MsgCancelAllOrders(input: unknown, label: string = "value") {
  const record = asRecord(input);
  const prefix = label ? `${label}.` : "";
  return {
    sender: requireString(getField(record, "sender", "sender"), `${prefix}sender`),
    marketId: requireBigIntLike(getField(record, "marketId", "market_id"), `${prefix}marketId`),
  };
}

function mapAultExchangeV1beta1MsgCancelOrder(input: unknown, label: string = "value") {
  const record = asRecord(input);
  const prefix = label ? `${label}.` : "";
  return {
    sender: requireString(getField(record, "sender", "sender"), `${prefix}sender`),
    orderId: requireBytes(getField(record, "orderId", "order_id"), `${prefix}orderId`),
  };
}

function mapAultExchangeV1beta1MsgCreateMarket(input: unknown, label: string = "value") {
  const record = asRecord(input);
  const prefix = label ? `${label}.` : "";
  return {
    sender: requireString(getField(record, "sender", "sender"), `${prefix}sender`),
    baseDenom: requireString(getField(record, "baseDenom", "base_denom"), `${prefix}baseDenom`),
    quoteDenom: requireString(getField(record, "quoteDenom", "quote_denom"), `${prefix}quoteDenom`),
  };
}

function mapAultExchangeV1beta1MsgPlaceLimitOrder(input: unknown, label: string = "value") {
  const record = asRecord(input);
  const prefix = label ? `${label}.` : "";
  return {
    sender: requireString(getField(record, "sender", "sender"), `${prefix}sender`),
    marketId: requireBigIntLike(getField(record, "marketId", "market_id"), `${prefix}marketId`),
    isBuy: requireBool(getField(record, "isBuy", "is_buy"), `${prefix}isBuy`),
    price: requireString(getField(record, "price", "price"), `${prefix}price`),
    quantity: requireString(getField(record, "quantity", "quantity"), `${prefix}quantity`),
    lifespan: requireDuration(getField(record, "lifespan", "lifespan"), `${prefix}lifespan`),
  };
}

function mapAultExchangeV1beta1MsgPlaceMarketOrder(input: unknown, label: string = "value") {
  const record = asRecord(input);
  const prefix = label ? `${label}.` : "";
  return {
    sender: requireString(getField(record, "sender", "sender"), `${prefix}sender`),
    marketId: requireBigIntLike(getField(record, "marketId", "market_id"), `${prefix}marketId`),
    isBuy: requireBool(getField(record, "isBuy", "is_buy"), `${prefix}isBuy`),
    quantity: requireString(getField(record, "quantity", "quantity"), `${prefix}quantity`),
  };
}

function mapAultExchangeV1beta1MsgUpdateMarketParams(input: unknown, label: string = "value") {
  const record = asRecord(input);
  const prefix = label ? `${label}.` : "";
  return {
    authority: requireString(getField(record, "authority", "authority"), `${prefix}authority`),
    updates: requireRecordArray(getField(record, "updates", "updates"), `${prefix}updates`).map((item, index) => mapAultExchangeV1beta1MarketParamUpdate(item, `${prefix}updates[${index}]`)),
  };
}

function mapAultLicenseV1MsgApproveMember(input: unknown, label: string = "value") {
  const record = asRecord(input);
  const prefix = label ? `${label}.` : "";
  return {
    authority: requireString(getField(record, "authority", "authority"), `${prefix}authority`),
    member: requireString(getField(record, "member", "member"), `${prefix}member`),
  };
}

function mapAultLicenseV1MsgBatchApproveMember(input: unknown, label: string = "value") {
  const record = asRecord(input);
  const prefix = label ? `${label}.` : "";
  return {
    authority: requireString(getField(record, "authority", "authority"), `${prefix}authority`),
    members: requireStringArray(getField(record, "members", "members"), `${prefix}members`),
  };
}

function mapAultLicenseV1MsgBatchMintLicense(input: unknown, label: string = "value") {
  const record = asRecord(input);
  const prefix = label ? `${label}.` : "";
  return {
    minter: requireString(getField(record, "minter", "minter"), `${prefix}minter`),
    to: requireStringArray(getField(record, "to", "to"), `${prefix}to`),
    uri: requireStringArray(getField(record, "uri", "uri"), `${prefix}uri`),
    reason: requireString(getField(record, "reason", "reason"), `${prefix}reason`),
  };
}

function mapAultLicenseV1MsgBatchRevokeMember(input: unknown, label: string = "value") {
  const record = asRecord(input);
  const prefix = label ? `${label}.` : "";
  return {
    authority: requireString(getField(record, "authority", "authority"), `${prefix}authority`),
    members: requireStringArray(getField(record, "members", "members"), `${prefix}members`),
  };
}

function mapAultLicenseV1MsgBurnLicense(input: unknown, label: string = "value") {
  const record = asRecord(input);
  const prefix = label ? `${label}.` : "";
  return {
    authority: requireString(getField(record, "authority", "authority"), `${prefix}authority`),
    id: requireBigIntLike(getField(record, "id", "id"), `${prefix}id`),
    reason: requireString(getField(record, "reason", "reason"), `${prefix}reason`),
  };
}

function mapAultLicenseV1MsgMintLicense(input: unknown, label: string = "value") {
  const record = asRecord(input);
  const prefix = label ? `${label}.` : "";
  return {
    minter: requireString(getField(record, "minter", "minter"), `${prefix}minter`),
    to: requireString(getField(record, "to", "to"), `${prefix}to`),
    uri: requireString(getField(record, "uri", "uri"), `${prefix}uri`),
    reason: requireString(getField(record, "reason", "reason"), `${prefix}reason`),
  };
}

function mapAultLicenseV1MsgRevokeLicense(input: unknown, label: string = "value") {
  const record = asRecord(input);
  const prefix = label ? `${label}.` : "";
  return {
    authority: requireString(getField(record, "authority", "authority"), `${prefix}authority`),
    id: requireBigIntLike(getField(record, "id", "id"), `${prefix}id`),
    reason: requireString(getField(record, "reason", "reason"), `${prefix}reason`),
  };
}

function mapAultLicenseV1MsgRevokeMember(input: unknown, label: string = "value") {
  const record = asRecord(input);
  const prefix = label ? `${label}.` : "";
  return {
    authority: requireString(getField(record, "authority", "authority"), `${prefix}authority`),
    member: requireString(getField(record, "member", "member"), `${prefix}member`),
  };
}

function mapAultLicenseV1MsgSetKYCApprovers(input: unknown, label: string = "value") {
  const record = asRecord(input);
  const prefix = label ? `${label}.` : "";
  return {
    authority: requireString(getField(record, "authority", "authority"), `${prefix}authority`),
    add: requireStringArray(getField(record, "add", "add"), `${prefix}add`),
    remove: requireStringArray(getField(record, "remove", "remove"), `${prefix}remove`),
  };
}

function mapAultLicenseV1MsgSetMinters(input: unknown, label: string = "value") {
  const record = asRecord(input);
  const prefix = label ? `${label}.` : "";
  return {
    authority: requireString(getField(record, "authority", "authority"), `${prefix}authority`),
    add: requireStringArray(getField(record, "add", "add"), `${prefix}add`),
    remove: requireStringArray(getField(record, "remove", "remove"), `${prefix}remove`),
  };
}

function mapAultLicenseV1MsgSetTokenURI(input: unknown, label: string = "value") {
  const record = asRecord(input);
  const prefix = label ? `${label}.` : "";
  return {
    minter: requireString(getField(record, "minter", "minter"), `${prefix}minter`),
    id: requireBigIntLike(getField(record, "id", "id"), `${prefix}id`),
    uri: requireString(getField(record, "uri", "uri"), `${prefix}uri`),
  };
}

function mapAultLicenseV1MsgTransferLicense(input: unknown, label: string = "value") {
  const record = asRecord(input);
  const prefix = label ? `${label}.` : "";
  return {
    from: requireString(getField(record, "from", "from"), `${prefix}from`),
    to: requireString(getField(record, "to", "to"), `${prefix}to`),
    licenseId: requireBigIntLike(getField(record, "licenseId", "license_id"), `${prefix}licenseId`),
    reason: requireString(getField(record, "reason", "reason"), `${prefix}reason`),
  };
}

function mapAultLicenseV1MsgUpdateParams(input: unknown, label: string = "value") {
  const record = asRecord(input);
  const prefix = label ? `${label}.` : "";
  return {
    authority: requireString(getField(record, "authority", "authority"), `${prefix}authority`),
    params: mapAultLicenseV1Params(asRecord(getField(record, "params", "params")), `${prefix}params`),
  };
}

function mapAultLicenseV1Params(input: unknown, label: string = "value") {
  const record = asRecord(input);
  const prefix = label ? `${label}.` : "";
  return {
    className: requireStringOrDefault(getField(record, "className", "class_name"), `${prefix}className`),
    classSymbol: requireStringOrDefault(getField(record, "classSymbol", "class_symbol"), `${prefix}classSymbol`),
    baseTokenUri: requireStringOrDefault(getField(record, "baseTokenUri", "base_token_uri"), `${prefix}baseTokenUri`),
    mintingPaused: requireBoolOrDefault(getField(record, "mintingPaused", "minting_paused"), `${prefix}mintingPaused`),
    supplyCap: requireBigIntOrDefault(getField(record, "supplyCap", "supply_cap"), `${prefix}supplyCap`),
    allowMetadataUpdate: requireBoolOrDefault(getField(record, "allowMetadataUpdate", "allow_metadata_update"), `${prefix}allowMetadataUpdate`),
    adminCanRevoke: requireBoolOrDefault(getField(record, "adminCanRevoke", "admin_can_revoke"), `${prefix}adminCanRevoke`),
    adminCanBurn: requireBoolOrDefault(getField(record, "adminCanBurn", "admin_can_burn"), `${prefix}adminCanBurn`),
    maxBatchSize: requireUint32OrDefault(getField(record, "maxBatchSize", "max_batch_size"), `${prefix}maxBatchSize`),
    transferUnlockDays: requireUint32OrDefault(getField(record, "transferUnlockDays", "transfer_unlock_days"), `${prefix}transferUnlockDays`),
    enableTransfers: requireBoolOrDefault(getField(record, "enableTransfers", "enable_transfers"), `${prefix}enableTransfers`),
    minterAllowedMsgs: requireStringArrayOrDefault(getField(record, "minterAllowedMsgs", "minter_allowed_msgs"), `${prefix}minterAllowedMsgs`),
    kycApproverAllowedMsgs: requireStringArrayOrDefault(getField(record, "kycApproverAllowedMsgs", "kyc_approver_allowed_msgs"), `${prefix}kycApproverAllowedMsgs`),
    freeMaxGasLimit: requireBigIntOrDefault(getField(record, "freeMaxGasLimit", "free_max_gas_limit"), `${prefix}freeMaxGasLimit`),
    maxVotingPowerPerAddress: requireBigIntOrDefault(getField(record, "maxVotingPowerPerAddress", "max_voting_power_per_address"), `${prefix}maxVotingPowerPerAddress`),
  };
}

function mapAultMinerV1MsgBatchSubmitWork(input: unknown, label: string = "value") {
  const record = asRecord(input);
  const prefix = label ? `${label}.` : "";
  return {
    submissions: requireRecordArray(getField(record, "submissions", "submissions"), `${prefix}submissions`).map((item, index) => mapAultMinerV1WorkSubmission(item, `${prefix}submissions[${index}]`)),
    submitter: requireString(getField(record, "submitter", "submitter"), `${prefix}submitter`),
  };
}

function mapAultMinerV1MsgCancelMiningDelegation(input: unknown, label: string = "value") {
  const record = asRecord(input);
  const prefix = label ? `${label}.` : "";
  return {
    owner: requireString(getField(record, "owner", "owner"), `${prefix}owner`),
    licenseIds: requireBigIntArray(getField(record, "licenseIds", "license_ids"), `${prefix}licenseIds`),
  };
}

function mapAultMinerV1MsgDelegateMining(input: unknown, label: string = "value") {
  const record = asRecord(input);
  const prefix = label ? `${label}.` : "";
  return {
    owner: requireString(getField(record, "owner", "owner"), `${prefix}owner`),
    licenseIds: requireBigIntArray(getField(record, "licenseIds", "license_ids"), `${prefix}licenseIds`),
    operator: requireString(getField(record, "operator", "operator"), `${prefix}operator`),
  };
}

function mapAultMinerV1MsgRedelegateMining(input: unknown, label: string = "value") {
  const record = asRecord(input);
  const prefix = label ? `${label}.` : "";
  return {
    owner: requireString(getField(record, "owner", "owner"), `${prefix}owner`),
    licenseIds: requireBigIntArray(getField(record, "licenseIds", "license_ids"), `${prefix}licenseIds`),
    newOperator: requireString(getField(record, "newOperator", "new_operator"), `${prefix}newOperator`),
  };
}

function mapAultMinerV1MsgRegisterOperator(input: unknown, label: string = "value") {
  const record = asRecord(input);
  const prefix = label ? `${label}.` : "";
  return {
    operator: requireString(getField(record, "operator", "operator"), `${prefix}operator`),
    commissionRate: requireUint32Like(getField(record, "commissionRate", "commission_rate"), `${prefix}commissionRate`),
    commissionRecipient: requireStringOrDefault(getField(record, "commissionRecipient", "commission_recipient"), `${prefix}commissionRecipient`),
  };
}

function mapAultMinerV1MsgSetOwnerVrfKey(input: unknown, label: string = "value") {
  const record = asRecord(input);
  const prefix = label ? `${label}.` : "";
  return {
    vrfPubkey: requireBytes(getField(record, "vrfPubkey", "vrf_pubkey"), `${prefix}vrfPubkey`),
    possessionProof: requireBytes(getField(record, "possessionProof", "possession_proof"), `${prefix}possessionProof`),
    nonce: requireBigIntLike(getField(record, "nonce", "nonce"), `${prefix}nonce`),
    owner: requireString(getField(record, "owner", "owner"), `${prefix}owner`),
  };
}

function mapAultMinerV1MsgSubmitWork(input: unknown, label: string = "value") {
  const record = asRecord(input);
  const prefix = label ? `${label}.` : "";
  return {
    licenseId: requireBigIntLike(getField(record, "licenseId", "license_id"), `${prefix}licenseId`),
    epoch: requireBigIntLike(getField(record, "epoch", "epoch"), `${prefix}epoch`),
    y: requireBytes(getField(record, "y", "y"), `${prefix}y`),
    proof: requireBytes(getField(record, "proof", "proof"), `${prefix}proof`),
    submitter: requireString(getField(record, "submitter", "submitter"), `${prefix}submitter`),
  };
}

function mapAultMinerV1MsgUnregisterOperator(input: unknown, label: string = "value") {
  const record = asRecord(input);
  const prefix = label ? `${label}.` : "";
  return {
    operator: requireString(getField(record, "operator", "operator"), `${prefix}operator`),
  };
}

function mapAultMinerV1MsgUpdateOperatorInfo(input: unknown, label: string = "value") {
  const record = asRecord(input);
  const prefix = label ? `${label}.` : "";
  return {
    operator: requireString(getField(record, "operator", "operator"), `${prefix}operator`),
    newCommissionRate: requireUint32Like(getField(record, "newCommissionRate", "new_commission_rate"), `${prefix}newCommissionRate`),
    newCommissionRecipient: requireStringOrDefault(getField(record, "newCommissionRecipient", "new_commission_recipient"), `${prefix}newCommissionRecipient`),
  };
}

function mapAultMinerV1MsgUpdateParams(input: unknown, label: string = "value") {
  const record = asRecord(input);
  const prefix = label ? `${label}.` : "";
  return {
    authority: requireString(getField(record, "authority", "authority"), `${prefix}authority`),
    params: mapAultMinerV1Params(asRecord(getField(record, "params", "params")), `${prefix}params`),
  };
}

function mapAultMinerV1Params(input: unknown, label: string = "value") {
  const record = asRecord(input);
  const prefix = label ? `${label}.` : "";
  return {
    epochLengthSeconds: requireBigIntOrDefault(getField(record, "epochLengthSeconds", "epoch_length_seconds"), `${prefix}epochLengthSeconds`),
    targetWinnersPerEpoch: requireUint32OrDefault(getField(record, "targetWinnersPerEpoch", "target_winners_per_epoch"), `${prefix}targetWinnersPerEpoch`),
    maxWinnersPerEpoch: requireUint32OrDefault(getField(record, "maxWinnersPerEpoch", "max_winners_per_epoch"), `${prefix}maxWinnersPerEpoch`),
    submissionWindowSeconds: requireUint32OrDefault(getField(record, "submissionWindowSeconds", "submission_window_seconds"), `${prefix}submissionWindowSeconds`),
    controllerAlphaQ16: requireUint32OrDefault(getField(record, "controllerAlphaQ16", "controller_alpha_q16"), `${prefix}controllerAlphaQ16`),
    controllerWindow: requireUint32OrDefault(getField(record, "controllerWindow", "controller_window"), `${prefix}controllerWindow`),
    thresholdMin: requireStringOrDefault(getField(record, "thresholdMin", "threshold_min"), `${prefix}thresholdMin`),
    thresholdMax: requireStringOrDefault(getField(record, "thresholdMax", "threshold_max"), `${prefix}thresholdMax`),
    beaconWindowEpochs: requireUint32OrDefault(getField(record, "beaconWindowEpochs", "beacon_window_epochs"), `${prefix}beaconWindowEpochs`),
    keyRotationCooldownSeconds: requireBigIntOrDefault(getField(record, "keyRotationCooldownSeconds", "key_rotation_cooldown_seconds"), `${prefix}keyRotationCooldownSeconds`),
    vrfVerifyGas: requireUint32OrDefault(getField(record, "vrfVerifyGas", "vrf_verify_gas"), `${prefix}vrfVerifyGas`),
    minKeyAgeEpochs: requireUint32OrDefault(getField(record, "minKeyAgeEpochs", "min_key_age_epochs"), `${prefix}minKeyAgeEpochs`),
    initialEmissionPerEpoch: requireStringOrDefault(getField(record, "initialEmissionPerEpoch", "initial_emission_per_epoch"), `${prefix}initialEmissionPerEpoch`),
    emissionDecayRate: requireStringOrDefault(getField(record, "emissionDecayRate", "emission_decay_rate"), `${prefix}emissionDecayRate`),
    maxEmissionYears: requireUint32OrDefault(getField(record, "maxEmissionYears", "max_emission_years"), `${prefix}maxEmissionYears`),
    maxPayoutsPerBlock: requireUint32OrDefault(getField(record, "maxPayoutsPerBlock", "max_payouts_per_block"), `${prefix}maxPayoutsPerBlock`),
    maxEpochsPerBlock: requireBigIntOrDefault(getField(record, "maxEpochsPerBlock", "max_epochs_per_block"), `${prefix}maxEpochsPerBlock`),
    stakingRewardPercentage: requireUint32OrDefault(getField(record, "stakingRewardPercentage", "staking_reward_percentage"), `${prefix}stakingRewardPercentage`),
    maxCommissionRate: requireUint32OrDefault(getField(record, "maxCommissionRate", "max_commission_rate"), `${prefix}maxCommissionRate`),
    maxCommissionRateIncreasePerEpoch: requireUint32OrDefault(getField(record, "maxCommissionRateIncreasePerEpoch", "max_commission_rate_increase_per_epoch"), `${prefix}maxCommissionRateIncreasePerEpoch`),
    freeMiningUntilEpoch: requireBigIntOrDefault(getField(record, "freeMiningUntilEpoch", "free_mining_until_epoch"), `${prefix}freeMiningUntilEpoch`),
    freeMiningMaxGasLimit: requireBigIntOrDefault(getField(record, "freeMiningMaxGasLimit", "free_mining_max_gas_limit"), `${prefix}freeMiningMaxGasLimit`),
    minerAllowedMsgs: requireStringArrayOrDefault(getField(record, "minerAllowedMsgs", "miner_allowed_msgs"), `${prefix}minerAllowedMsgs`),
    maxFreeTxPerEpoch: requireUint32OrDefault(getField(record, "maxFreeTxPerEpoch", "max_free_tx_per_epoch"), `${prefix}maxFreeTxPerEpoch`),
  };
}

function mapAultMinerV1WorkSubmission(input: unknown, label: string = "value") {
  const record = asRecord(input);
  const prefix = label ? `${label}.` : "";
  return {
    licenseId: requireBigIntLike(getField(record, "licenseId", "license_id"), `${prefix}licenseId`),
    epoch: requireBigIntLike(getField(record, "epoch", "epoch"), `${prefix}epoch`),
    y: requireBytes(getField(record, "y", "y"), `${prefix}y`),
    proof: requireBytes(getField(record, "proof", "proof"), `${prefix}proof`),
  };
}

function mapCosmosBaseV1beta1Coin(input: unknown, label: string = "value") {
  const record = asRecord(input);
  const prefix = label ? `${label}.` : "";
  return {
    denom: requireString(getField(record, "denom", "denom"), `${prefix}denom`),
    amount: requireString(getField(record, "amount", "amount"), `${prefix}amount`),
  };
}

function mapCosmosDistributionV1beta1MsgWithdrawDelegatorReward(input: unknown, label: string = "value") {
  const record = asRecord(input);
  const prefix = label ? `${label}.` : "";
  return {
    delegatorAddress: requireString(getField(record, "delegatorAddress", "delegator_address"), `${prefix}delegatorAddress`),
    validatorAddress: requireString(getField(record, "validatorAddress", "validator_address"), `${prefix}validatorAddress`),
  };
}

function mapCosmosStakingV1beta1MsgBeginRedelegate(input: unknown, label: string = "value") {
  const record = asRecord(input);
  const prefix = label ? `${label}.` : "";
  return {
    delegatorAddress: requireString(getField(record, "delegatorAddress", "delegator_address"), `${prefix}delegatorAddress`),
    validatorSrcAddress: requireString(getField(record, "validatorSrcAddress", "validator_src_address"), `${prefix}validatorSrcAddress`),
    validatorDstAddress: requireString(getField(record, "validatorDstAddress", "validator_dst_address"), `${prefix}validatorDstAddress`),
    amount: mapCosmosBaseV1beta1Coin(asRecord(getField(record, "amount", "amount")), `${prefix}amount`),
  };
}

function mapCosmosStakingV1beta1MsgDelegate(input: unknown, label: string = "value") {
  const record = asRecord(input);
  const prefix = label ? `${label}.` : "";
  return {
    delegatorAddress: requireString(getField(record, "delegatorAddress", "delegator_address"), `${prefix}delegatorAddress`),
    validatorAddress: requireString(getField(record, "validatorAddress", "validator_address"), `${prefix}validatorAddress`),
    amount: mapCosmosBaseV1beta1Coin(asRecord(getField(record, "amount", "amount")), `${prefix}amount`),
  };
}

function mapCosmosStakingV1beta1MsgUndelegate(input: unknown, label: string = "value") {
  const record = asRecord(input);
  const prefix = label ? `${label}.` : "";
  return {
    delegatorAddress: requireString(getField(record, "delegatorAddress", "delegator_address"), `${prefix}delegatorAddress`),
    validatorAddress: requireString(getField(record, "validatorAddress", "validator_address"), `${prefix}validatorAddress`),
    amount: mapCosmosBaseV1beta1Coin(asRecord(getField(record, "amount", "amount")), `${prefix}amount`),
  };
}

export const MSG_ENCODERS: Record<string, (value: unknown) => Uint8Array> = {
  "/ault.exchange.v1beta1.MsgCancelAllOrders": (value: unknown) =>
    MsgCancelAllOrders.encode(MsgCancelAllOrders.fromPartial(mapAultExchangeV1beta1MsgCancelAllOrders(value))).finish(),
  "/ault.exchange.v1beta1.MsgCancelOrder": (value: unknown) =>
    MsgCancelOrder.encode(MsgCancelOrder.fromPartial(mapAultExchangeV1beta1MsgCancelOrder(value))).finish(),
  "/ault.exchange.v1beta1.MsgCreateMarket": (value: unknown) =>
    MsgCreateMarket.encode(MsgCreateMarket.fromPartial(mapAultExchangeV1beta1MsgCreateMarket(value))).finish(),
  "/ault.exchange.v1beta1.MsgPlaceLimitOrder": (value: unknown) =>
    MsgPlaceLimitOrder.encode(MsgPlaceLimitOrder.fromPartial(mapAultExchangeV1beta1MsgPlaceLimitOrder(value))).finish(),
  "/ault.exchange.v1beta1.MsgPlaceMarketOrder": (value: unknown) =>
    MsgPlaceMarketOrder.encode(MsgPlaceMarketOrder.fromPartial(mapAultExchangeV1beta1MsgPlaceMarketOrder(value))).finish(),
  "/ault.exchange.v1beta1.MsgUpdateMarketParams": (value: unknown) =>
    MsgUpdateMarketParams.encode(MsgUpdateMarketParams.fromPartial(mapAultExchangeV1beta1MsgUpdateMarketParams(value))).finish(),
  "/ault.license.v1.MsgApproveMember": (value: unknown) =>
    MsgApproveMember.encode(MsgApproveMember.fromPartial(mapAultLicenseV1MsgApproveMember(value))).finish(),
  "/ault.license.v1.MsgBatchApproveMember": (value: unknown) =>
    MsgBatchApproveMember.encode(MsgBatchApproveMember.fromPartial(mapAultLicenseV1MsgBatchApproveMember(value))).finish(),
  "/ault.license.v1.MsgBatchMintLicense": (value: unknown) =>
    MsgBatchMintLicense.encode(MsgBatchMintLicense.fromPartial(mapAultLicenseV1MsgBatchMintLicense(value))).finish(),
  "/ault.license.v1.MsgBatchRevokeMember": (value: unknown) =>
    MsgBatchRevokeMember.encode(MsgBatchRevokeMember.fromPartial(mapAultLicenseV1MsgBatchRevokeMember(value))).finish(),
  "/ault.license.v1.MsgBurnLicense": (value: unknown) =>
    MsgBurnLicense.encode(MsgBurnLicense.fromPartial(mapAultLicenseV1MsgBurnLicense(value))).finish(),
  "/ault.license.v1.MsgMintLicense": (value: unknown) =>
    MsgMintLicense.encode(MsgMintLicense.fromPartial(mapAultLicenseV1MsgMintLicense(value))).finish(),
  "/ault.license.v1.MsgRevokeLicense": (value: unknown) =>
    MsgRevokeLicense.encode(MsgRevokeLicense.fromPartial(mapAultLicenseV1MsgRevokeLicense(value))).finish(),
  "/ault.license.v1.MsgRevokeMember": (value: unknown) =>
    MsgRevokeMember.encode(MsgRevokeMember.fromPartial(mapAultLicenseV1MsgRevokeMember(value))).finish(),
  "/ault.license.v1.MsgSetKYCApprovers": (value: unknown) =>
    MsgSetKYCApprovers.encode(MsgSetKYCApprovers.fromPartial(mapAultLicenseV1MsgSetKYCApprovers(value))).finish(),
  "/ault.license.v1.MsgSetMinters": (value: unknown) =>
    MsgSetMinters.encode(MsgSetMinters.fromPartial(mapAultLicenseV1MsgSetMinters(value))).finish(),
  "/ault.license.v1.MsgSetTokenURI": (value: unknown) =>
    MsgSetTokenURI.encode(MsgSetTokenURI.fromPartial(mapAultLicenseV1MsgSetTokenURI(value))).finish(),
  "/ault.license.v1.MsgTransferLicense": (value: unknown) =>
    MsgTransferLicense.encode(MsgTransferLicense.fromPartial(mapAultLicenseV1MsgTransferLicense(value))).finish(),
  "/ault.license.v1.MsgUpdateParams": (value: unknown) =>
    MsgUpdateParamsAultLicenseV1.encode(MsgUpdateParamsAultLicenseV1.fromPartial(mapAultLicenseV1MsgUpdateParams(value))).finish(),
  "/ault.miner.v1.MsgBatchSubmitWork": (value: unknown) =>
    MsgBatchSubmitWork.encode(MsgBatchSubmitWork.fromPartial(mapAultMinerV1MsgBatchSubmitWork(value))).finish(),
  "/ault.miner.v1.MsgCancelMiningDelegation": (value: unknown) =>
    MsgCancelMiningDelegation.encode(MsgCancelMiningDelegation.fromPartial(mapAultMinerV1MsgCancelMiningDelegation(value))).finish(),
  "/ault.miner.v1.MsgDelegateMining": (value: unknown) =>
    MsgDelegateMining.encode(MsgDelegateMining.fromPartial(mapAultMinerV1MsgDelegateMining(value))).finish(),
  "/ault.miner.v1.MsgRedelegateMining": (value: unknown) =>
    MsgRedelegateMining.encode(MsgRedelegateMining.fromPartial(mapAultMinerV1MsgRedelegateMining(value))).finish(),
  "/ault.miner.v1.MsgRegisterOperator": (value: unknown) =>
    MsgRegisterOperator.encode(MsgRegisterOperator.fromPartial(mapAultMinerV1MsgRegisterOperator(value))).finish(),
  "/ault.miner.v1.MsgSetOwnerVrfKey": (value: unknown) =>
    MsgSetOwnerVrfKey.encode(MsgSetOwnerVrfKey.fromPartial(mapAultMinerV1MsgSetOwnerVrfKey(value))).finish(),
  "/ault.miner.v1.MsgSubmitWork": (value: unknown) =>
    MsgSubmitWork.encode(MsgSubmitWork.fromPartial(mapAultMinerV1MsgSubmitWork(value))).finish(),
  "/ault.miner.v1.MsgUnregisterOperator": (value: unknown) =>
    MsgUnregisterOperator.encode(MsgUnregisterOperator.fromPartial(mapAultMinerV1MsgUnregisterOperator(value))).finish(),
  "/ault.miner.v1.MsgUpdateOperatorInfo": (value: unknown) =>
    MsgUpdateOperatorInfo.encode(MsgUpdateOperatorInfo.fromPartial(mapAultMinerV1MsgUpdateOperatorInfo(value))).finish(),
  "/ault.miner.v1.MsgUpdateParams": (value: unknown) =>
    MsgUpdateParamsAultMinerV1.encode(MsgUpdateParamsAultMinerV1.fromPartial(mapAultMinerV1MsgUpdateParams(value))).finish(),
  "/cosmos.distribution.v1beta1.MsgWithdrawDelegatorReward": (value: unknown) =>
    MsgWithdrawDelegatorReward.encode(MsgWithdrawDelegatorReward.fromPartial(mapCosmosDistributionV1beta1MsgWithdrawDelegatorReward(value))).finish(),
  "/cosmos.staking.v1beta1.MsgBeginRedelegate": (value: unknown) =>
    MsgBeginRedelegate.encode(MsgBeginRedelegate.fromPartial(mapCosmosStakingV1beta1MsgBeginRedelegate(value))).finish(),
  "/cosmos.staking.v1beta1.MsgDelegate": (value: unknown) =>
    MsgDelegate.encode(MsgDelegate.fromPartial(mapCosmosStakingV1beta1MsgDelegate(value))).finish(),
  "/cosmos.staking.v1beta1.MsgUndelegate": (value: unknown) =>
    MsgUndelegate.encode(MsgUndelegate.fromPartial(mapCosmosStakingV1beta1MsgUndelegate(value))).finish(),
};
