// Code generated by scripts/generate-eip712-registry.mjs. DO NOT EDIT.
import type { Eip712Msg } from "./builder";
import type { MsgCancelAllOrders, MsgCancelOrder, MsgCreateMarket, MsgPlaceLimitOrder, MsgPlaceMarketOrder, MsgUpdateMarketParams } from "../proto/gen/ault/exchange/v1beta1/tx";
import type { MsgApproveMember, MsgBatchApproveMember, MsgBatchMintLicense, MsgBatchRevokeMember, MsgBurnLicense, MsgMintLicense, MsgRevokeLicense, MsgRevokeMember, MsgSetKYCApprovers, MsgSetMinters, MsgSetTokenURI, MsgTransferLicense, MsgUpdateParams as MsgUpdateParamsAultLicenseV1 } from "../proto/gen/ault/license/v1/tx";
import type { MsgBatchSubmitWork, MsgCancelMiningDelegation, MsgDelegateMining, MsgRedelegateMining, MsgRegisterOperator, MsgSetOwnerVrfKey, MsgSubmitWork, MsgUnregisterOperator, MsgUpdateOperatorInfo, MsgUpdateParams as MsgUpdateParamsAultMinerV1 } from "../proto/gen/ault/miner/v1/tx";
import type { MsgWithdrawDelegatorReward } from "../proto/gen/cosmos/distribution/v1beta1/tx";
import type { MsgBeginRedelegate, MsgDelegate, MsgUndelegate } from "../proto/gen/cosmos/staking/v1beta1/tx";

const buildMsg = <TTypeUrl extends string, TValue>(typeUrl: TTypeUrl, value: TValue): Eip712Msg<TValue, TTypeUrl> => ({
  typeUrl,
  value,
});

export const msg = {
  distribution: {
    withdrawDelegatorReward: (value: MsgWithdrawDelegatorReward) => buildMsg("/cosmos.distribution.v1beta1.MsgWithdrawDelegatorReward", value),
  },
  exchange: {
    cancelAllOrders: (value: MsgCancelAllOrders) => buildMsg("/ault.exchange.v1beta1.MsgCancelAllOrders", value),
    cancelOrder: (value: MsgCancelOrder) => buildMsg("/ault.exchange.v1beta1.MsgCancelOrder", value),
    createMarket: (value: MsgCreateMarket) => buildMsg("/ault.exchange.v1beta1.MsgCreateMarket", value),
    placeLimitOrder: (value: MsgPlaceLimitOrder) => buildMsg("/ault.exchange.v1beta1.MsgPlaceLimitOrder", value),
    placeMarketOrder: (value: MsgPlaceMarketOrder) => buildMsg("/ault.exchange.v1beta1.MsgPlaceMarketOrder", value),
    updateMarketParams: (value: MsgUpdateMarketParams) => buildMsg("/ault.exchange.v1beta1.MsgUpdateMarketParams", value),
  },
  license: {
    approveMember: (value: MsgApproveMember) => buildMsg("/ault.license.v1.MsgApproveMember", value),
    batchApproveMember: (value: MsgBatchApproveMember) => buildMsg("/ault.license.v1.MsgBatchApproveMember", value),
    batchMintLicense: (value: MsgBatchMintLicense) => buildMsg("/ault.license.v1.MsgBatchMintLicense", value),
    batchRevokeMember: (value: MsgBatchRevokeMember) => buildMsg("/ault.license.v1.MsgBatchRevokeMember", value),
    burnLicense: (value: MsgBurnLicense) => buildMsg("/ault.license.v1.MsgBurnLicense", value),
    mintLicense: (value: MsgMintLicense) => buildMsg("/ault.license.v1.MsgMintLicense", value),
    revokeLicense: (value: MsgRevokeLicense) => buildMsg("/ault.license.v1.MsgRevokeLicense", value),
    revokeMember: (value: MsgRevokeMember) => buildMsg("/ault.license.v1.MsgRevokeMember", value),
    setKYCApprovers: (value: MsgSetKYCApprovers) => buildMsg("/ault.license.v1.MsgSetKYCApprovers", value),
    setMinters: (value: MsgSetMinters) => buildMsg("/ault.license.v1.MsgSetMinters", value),
    setTokenURI: (value: MsgSetTokenURI) => buildMsg("/ault.license.v1.MsgSetTokenURI", value),
    transferLicense: (value: MsgTransferLicense) => buildMsg("/ault.license.v1.MsgTransferLicense", value),
    updateParams: (value: MsgUpdateParamsAultLicenseV1) => buildMsg("/ault.license.v1.MsgUpdateParams", value),
  },
  miner: {
    batchSubmitWork: (value: MsgBatchSubmitWork) => buildMsg("/ault.miner.v1.MsgBatchSubmitWork", value),
    cancelMiningDelegation: (value: MsgCancelMiningDelegation) => buildMsg("/ault.miner.v1.MsgCancelMiningDelegation", value),
    delegateMining: (value: MsgDelegateMining) => buildMsg("/ault.miner.v1.MsgDelegateMining", value),
    redelegateMining: (value: MsgRedelegateMining) => buildMsg("/ault.miner.v1.MsgRedelegateMining", value),
    registerOperator: (value: MsgRegisterOperator) => buildMsg("/ault.miner.v1.MsgRegisterOperator", value),
    setOwnerVrfKey: (value: MsgSetOwnerVrfKey) => buildMsg("/ault.miner.v1.MsgSetOwnerVrfKey", value),
    submitWork: (value: MsgSubmitWork) => buildMsg("/ault.miner.v1.MsgSubmitWork", value),
    unregisterOperator: (value: MsgUnregisterOperator) => buildMsg("/ault.miner.v1.MsgUnregisterOperator", value),
    updateOperatorInfo: (value: MsgUpdateOperatorInfo) => buildMsg("/ault.miner.v1.MsgUpdateOperatorInfo", value),
    updateParams: (value: MsgUpdateParamsAultMinerV1) => buildMsg("/ault.miner.v1.MsgUpdateParams", value),
  },
  staking: {
    beginRedelegate: (value: MsgBeginRedelegate) => buildMsg("/cosmos.staking.v1beta1.MsgBeginRedelegate", value),
    delegate: (value: MsgDelegate) => buildMsg("/cosmos.staking.v1beta1.MsgDelegate", value),
    undelegate: (value: MsgUndelegate) => buildMsg("/cosmos.staking.v1beta1.MsgUndelegate", value),
  },
} as const;

export type AnyEip712Msg =
  | Eip712Msg<MsgCancelAllOrders, "/ault.exchange.v1beta1.MsgCancelAllOrders">
  | Eip712Msg<MsgCancelOrder, "/ault.exchange.v1beta1.MsgCancelOrder">
  | Eip712Msg<MsgCreateMarket, "/ault.exchange.v1beta1.MsgCreateMarket">
  | Eip712Msg<MsgPlaceLimitOrder, "/ault.exchange.v1beta1.MsgPlaceLimitOrder">
  | Eip712Msg<MsgPlaceMarketOrder, "/ault.exchange.v1beta1.MsgPlaceMarketOrder">
  | Eip712Msg<MsgUpdateMarketParams, "/ault.exchange.v1beta1.MsgUpdateMarketParams">
  | Eip712Msg<MsgApproveMember, "/ault.license.v1.MsgApproveMember">
  | Eip712Msg<MsgBatchApproveMember, "/ault.license.v1.MsgBatchApproveMember">
  | Eip712Msg<MsgBatchMintLicense, "/ault.license.v1.MsgBatchMintLicense">
  | Eip712Msg<MsgBatchRevokeMember, "/ault.license.v1.MsgBatchRevokeMember">
  | Eip712Msg<MsgBurnLicense, "/ault.license.v1.MsgBurnLicense">
  | Eip712Msg<MsgMintLicense, "/ault.license.v1.MsgMintLicense">
  | Eip712Msg<MsgRevokeLicense, "/ault.license.v1.MsgRevokeLicense">
  | Eip712Msg<MsgRevokeMember, "/ault.license.v1.MsgRevokeMember">
  | Eip712Msg<MsgSetKYCApprovers, "/ault.license.v1.MsgSetKYCApprovers">
  | Eip712Msg<MsgSetMinters, "/ault.license.v1.MsgSetMinters">
  | Eip712Msg<MsgSetTokenURI, "/ault.license.v1.MsgSetTokenURI">
  | Eip712Msg<MsgTransferLicense, "/ault.license.v1.MsgTransferLicense">
  | Eip712Msg<MsgUpdateParamsAultLicenseV1, "/ault.license.v1.MsgUpdateParams">
  | Eip712Msg<MsgBatchSubmitWork, "/ault.miner.v1.MsgBatchSubmitWork">
  | Eip712Msg<MsgCancelMiningDelegation, "/ault.miner.v1.MsgCancelMiningDelegation">
  | Eip712Msg<MsgDelegateMining, "/ault.miner.v1.MsgDelegateMining">
  | Eip712Msg<MsgRedelegateMining, "/ault.miner.v1.MsgRedelegateMining">
  | Eip712Msg<MsgRegisterOperator, "/ault.miner.v1.MsgRegisterOperator">
  | Eip712Msg<MsgSetOwnerVrfKey, "/ault.miner.v1.MsgSetOwnerVrfKey">
  | Eip712Msg<MsgSubmitWork, "/ault.miner.v1.MsgSubmitWork">
  | Eip712Msg<MsgUnregisterOperator, "/ault.miner.v1.MsgUnregisterOperator">
  | Eip712Msg<MsgUpdateOperatorInfo, "/ault.miner.v1.MsgUpdateOperatorInfo">
  | Eip712Msg<MsgUpdateParamsAultMinerV1, "/ault.miner.v1.MsgUpdateParams">
  | Eip712Msg<MsgWithdrawDelegatorReward, "/cosmos.distribution.v1beta1.MsgWithdrawDelegatorReward">
  | Eip712Msg<MsgBeginRedelegate, "/cosmos.staking.v1beta1.MsgBeginRedelegate">
  | Eip712Msg<MsgDelegate, "/cosmos.staking.v1beta1.MsgDelegate">
  | Eip712Msg<MsgUndelegate, "/cosmos.staking.v1beta1.MsgUndelegate">
;
