// Code generated by scripts/generate-eip712-registry.mjs. DO NOT EDIT.
import type { Eip712MsgTypeConfig } from "./registry";

export const EIP712_MSG_TYPES: Record<string, Eip712MsgTypeConfig> = {
  "/ault.exchange.v1beta1.MsgCancelAllOrders": {
    aminoType: "exchange/MsgCancelAllOrders",
    eip712TypeName: "TypeMsgCancelAllOrders",
    valueFields: [
      { name: "sender", type: "string" },
      { name: "market_id", type: "string" },
    ],
  },
  "/ault.exchange.v1beta1.MsgCancelOrder": {
    aminoType: "exchange/MsgCancelOrder",
    eip712TypeName: "TypeMsgCancelOrder",
    valueFields: [
      { name: "sender", type: "string" },
      { name: "order_id", type: "string" },
    ],
    legacyAminoRegistered: false,
  },
  "/ault.exchange.v1beta1.MsgCreateMarket": {
    aminoType: "exchange/MsgCreateMarket",
    eip712TypeName: "TypeMsgCreateMarket",
    valueFields: [
      { name: "sender", type: "string" },
      { name: "quote_denom", type: "string" },
      { name: "base_denom", type: "string" },
    ],
  },
  "/ault.exchange.v1beta1.MsgPlaceLimitOrder": {
    aminoType: "exchange/MsgPlaceLimitOrder",
    eip712TypeName: "TypeMsgPlaceLimitOrder",
    valueFields: [
      { name: "sender", type: "string" },
      { name: "quantity", type: "string" },
      { name: "price", type: "string" },
      { name: "market_id", type: "string" },
      { name: "lifespan", type: "string" },
      { name: "is_buy", type: "bool" },
    ],
    durationFields: [
      "lifespan",
    ],
  },
  "/ault.exchange.v1beta1.MsgPlaceMarketOrder": {
    aminoType: "exchange/MsgPlaceMarketOrder",
    eip712TypeName: "TypeMsgPlaceMarketOrder",
    valueFields: [
      { name: "sender", type: "string" },
      { name: "quantity", type: "string" },
      { name: "market_id", type: "string" },
      { name: "is_buy", type: "bool" },
    ],
  },
  "/ault.exchange.v1beta1.MsgUpdateMarketParams": {
    aminoType: "exchange/MsgUpdateMarketParams",
    eip712TypeName: "TypeMsgUpdateMarketParams",
    valueFields: [
      { name: "updates", type: "NESTED[]" },
      { name: "authority", type: "string" },
    ],
    nestedTypes: {
      updates: [
        { name: "taker_fee_rate", type: "string" },
        { name: "market_id", type: "string" },
        { name: "maker_fee_rate", type: "string" },
      ],
    },
  },
  "/ault.license.v1.MsgApproveMember": {
    aminoType: "license/MsgApproveMember",
    eip712TypeName: "TypeMsgApproveMember",
    valueFields: [
      { name: "member", type: "string" },
      { name: "authority", type: "string" },
    ],
  },
  "/ault.license.v1.MsgBatchApproveMember": {
    aminoType: "license/MsgBatchApproveMember",
    eip712TypeName: "TypeMsgBatchApproveMember",
    valueFields: [
      { name: "members", type: "string[]" },
      { name: "authority", type: "string" },
    ],
  },
  "/ault.license.v1.MsgBatchMintLicense": {
    aminoType: "license/MsgBatchMintLicense",
    eip712TypeName: "TypeMsgBatchMintLicense",
    valueFields: [
      { name: "uri", type: "string[]" },
      { name: "to", type: "string[]" },
      { name: "reason", type: "string" },
      { name: "minter", type: "string" },
    ],
  },
  "/ault.license.v1.MsgBatchRevokeMember": {
    aminoType: "license/MsgBatchRevokeMember",
    eip712TypeName: "TypeMsgBatchRevokeMember",
    valueFields: [
      { name: "members", type: "string[]" },
      { name: "authority", type: "string" },
    ],
  },
  "/ault.license.v1.MsgBurnLicense": {
    aminoType: "license/MsgBurnLicense",
    eip712TypeName: "TypeMsgBurnLicense",
    valueFields: [
      { name: "reason", type: "string" },
      { name: "id", type: "string" },
      { name: "authority", type: "string" },
    ],
  },
  "/ault.license.v1.MsgMintLicense": {
    aminoType: "license/MsgMintLicense",
    eip712TypeName: "TypeMsgMintLicense",
    valueFields: [
      { name: "uri", type: "string" },
      { name: "to", type: "string" },
      { name: "reason", type: "string" },
      { name: "minter", type: "string" },
    ],
  },
  "/ault.license.v1.MsgRevokeLicense": {
    aminoType: "license/MsgRevokeLicense",
    eip712TypeName: "TypeMsgRevokeLicense",
    valueFields: [
      { name: "reason", type: "string" },
      { name: "id", type: "string" },
      { name: "authority", type: "string" },
    ],
  },
  "/ault.license.v1.MsgRevokeMember": {
    aminoType: "license/MsgRevokeMember",
    eip712TypeName: "TypeMsgRevokeMember",
    valueFields: [
      { name: "member", type: "string" },
      { name: "authority", type: "string" },
    ],
  },
  "/ault.license.v1.MsgSetKYCApprovers": {
    aminoType: "license/MsgSetKYCApprovers",
    eip712TypeName: "TypeMsgSetKYCApprovers",
    valueFields: [
      { name: "remove", type: "string[]" },
      { name: "authority", type: "string" },
      { name: "add", type: "string[]" },
    ],
  },
  "/ault.license.v1.MsgSetMinters": {
    aminoType: "license/MsgSetMinters",
    eip712TypeName: "TypeMsgSetMinters",
    valueFields: [
      { name: "remove", type: "string[]" },
      { name: "authority", type: "string" },
      { name: "add", type: "string[]" },
    ],
  },
  "/ault.license.v1.MsgSetParams": {
    aminoType: "license/MsgSetParams",
    eip712TypeName: "TypeMsgSetParams",
    valueFields: [
      { name: "params", type: "NESTED" },
      { name: "authority", type: "string" },
    ],
    nestedTypes: {
      params: [
        { name: "transfer_unlock_days", type: "string" },
        { name: "supply_cap", type: "string" },
        { name: "minting_paused", type: "bool" },
        { name: "minter_allowed_msgs", type: "string[]" },
        { name: "max_voting_power_per_address", type: "string" },
        { name: "max_batch_mint_size", type: "string" },
        { name: "kyc_approver_allowed_msgs", type: "string[]" },
        { name: "free_max_gas_limit", type: "string" },
        { name: "enable_transfers", type: "bool" },
        { name: "class_symbol", type: "string" },
        { name: "class_name", type: "string" },
        { name: "base_token_uri", type: "string" },
        { name: "allow_metadata_update", type: "bool" },
        { name: "admin_can_revoke", type: "bool" },
        { name: "admin_can_burn", type: "bool" },
      ],
    },
  },
  "/ault.license.v1.MsgSetTokenURI": {
    aminoType: "license/MsgSetTokenURI",
    eip712TypeName: "TypeMsgSetTokenURI",
    valueFields: [
      { name: "uri", type: "string" },
      { name: "minter", type: "string" },
      { name: "id", type: "string" },
    ],
  },
  "/ault.license.v1.MsgTransferLicense": {
    aminoType: "license/MsgTransferLicense",
    eip712TypeName: "TypeMsgTransferLicense",
    valueFields: [
      { name: "to", type: "string" },
      { name: "reason", type: "string" },
      { name: "license_id", type: "string" },
      { name: "from", type: "string" },
    ],
  },
  "/ault.license.v1.MsgUpdateParams": {
    aminoType: "license/MsgUpdateParams",
    eip712TypeName: "TypeMsgUpdateParams",
    valueFields: [
      { name: "params", type: "NESTED" },
      { name: "authority", type: "string" },
    ],
    nestedTypes: {
      params: [
        { name: "transfer_unlock_days", type: "string" },
        { name: "supply_cap", type: "string" },
        { name: "minting_paused", type: "bool" },
        { name: "minter_allowed_msgs", type: "string[]" },
        { name: "max_voting_power_per_address", type: "string" },
        { name: "max_batch_mint_size", type: "string" },
        { name: "kyc_approver_allowed_msgs", type: "string[]" },
        { name: "free_max_gas_limit", type: "string" },
        { name: "enable_transfers", type: "bool" },
        { name: "class_symbol", type: "string" },
        { name: "class_name", type: "string" },
        { name: "base_token_uri", type: "string" },
        { name: "allow_metadata_update", type: "bool" },
        { name: "admin_can_revoke", type: "bool" },
        { name: "admin_can_burn", type: "bool" },
      ],
    },
  },
  "/ault.miner.v1.MsgBatchSubmitWork": {
    aminoType: "miner/MsgBatchSubmitWork",
    eip712TypeName: "TypeMsgBatchSubmitWork",
    valueFields: [
      { name: "submitter", type: "string" },
      { name: "submissions", type: "NESTED[]" },
    ],
    nestedTypes: {
      submissions: [
        { name: "y", type: "string" },
        { name: "proof", type: "string" },
        { name: "nonce", type: "string" },
        { name: "license_id", type: "string" },
        { name: "epoch", type: "string" },
      ],
    },
  },
  "/ault.miner.v1.MsgCancelMiningDelegation": {
    aminoType: "miner/MsgCancelMiningDelegation",
    eip712TypeName: "TypeMsgCancelMiningDelegation",
    valueFields: [
      { name: "owner", type: "string" },
      { name: "license_ids", type: "string[]" },
    ],
  },
  "/ault.miner.v1.MsgDelegateMining": {
    aminoType: "miner/MsgDelegateMining",
    eip712TypeName: "TypeMsgDelegateMining",
    valueFields: [
      { name: "owner", type: "string" },
      { name: "operator", type: "string" },
      { name: "license_ids", type: "string[]" },
    ],
  },
  "/ault.miner.v1.MsgRedelegateMining": {
    aminoType: "miner/MsgRedelegateMining",
    eip712TypeName: "TypeMsgRedelegateMining",
    valueFields: [
      { name: "owner", type: "string" },
      { name: "new_operator", type: "string" },
      { name: "license_ids", type: "string[]" },
    ],
  },
  "/ault.miner.v1.MsgRegisterOperator": {
    aminoType: "miner/MsgRegisterOperator",
    eip712TypeName: "TypeMsgRegisterOperator",
    valueFields: [
      { name: "operator", type: "string" },
      { name: "commission_recipient", type: "string" },
      { name: "commission_rate", type: "string" },
    ],
  },
  "/ault.miner.v1.MsgSetOwnerVrfKey": {
    aminoType: "miner/MsgSetOwnerVrfKey",
    eip712TypeName: "TypeMsgSetOwnerVrfKey",
    valueFields: [
      { name: "vrf_pubkey", type: "string" },
      { name: "possession_proof", type: "string" },
      { name: "owner", type: "string" },
      { name: "nonce", type: "string" },
    ],
  },
  "/ault.miner.v1.MsgSubmitWork": {
    aminoType: "miner/MsgSubmitWork",
    eip712TypeName: "TypeMsgSubmitWork",
    valueFields: [
      { name: "y", type: "string" },
      { name: "submitter", type: "string" },
      { name: "proof", type: "string" },
      { name: "nonce", type: "string" },
      { name: "license_id", type: "string" },
      { name: "epoch", type: "string" },
    ],
  },
  "/ault.miner.v1.MsgUnregisterOperator": {
    aminoType: "miner/MsgUnregisterOperator",
    eip712TypeName: "TypeMsgUnregisterOperator",
    valueFields: [
      { name: "operator", type: "string" },
    ],
  },
  "/ault.miner.v1.MsgUpdateOperatorInfo": {
    aminoType: "miner/MsgUpdateOperatorInfo",
    eip712TypeName: "TypeMsgUpdateOperatorInfo",
    valueFields: [
      { name: "operator", type: "string" },
      { name: "new_commission_recipient", type: "string" },
      { name: "new_commission_rate", type: "string" },
    ],
  },
  "/ault.miner.v1.MsgUpdateParams": {
    aminoType: "miner/MsgUpdateParams",
    eip712TypeName: "TypeMsgUpdateParams",
    valueFields: [
      { name: "params", type: "NESTED" },
      { name: "authority", type: "string" },
    ],
    nestedTypes: {
      params: [
        { name: "vrf_verify_gas", type: "string" },
        { name: "threshold_min", type: "string" },
        { name: "threshold_max", type: "string" },
        { name: "target_winners_per_epoch", type: "string" },
        { name: "submission_window_seconds", type: "string" },
        { name: "staking_reward_percentage", type: "string" },
        { name: "miner_allowed_msgs", type: "string[]" },
        { name: "min_key_age_epochs", type: "string" },
        { name: "max_winners_per_epoch", type: "string" },
        { name: "max_payouts_per_block", type: "string" },
        { name: "max_free_tx_per_epoch", type: "string" },
        { name: "max_epochs_per_block", type: "string" },
        { name: "max_emission_years", type: "string" },
        { name: "max_commission_rate_increase_per_epoch", type: "string" },
        { name: "max_commission_rate", type: "string" },
        { name: "key_rotation_cooldown_seconds", type: "string" },
        { name: "initial_emission_per_epoch", type: "string" },
        { name: "free_mining_until_epoch", type: "string" },
        { name: "free_mining_max_gas_limit", type: "string" },
        { name: "epoch_length_seconds", type: "string" },
        { name: "emission_decay_rate", type: "string" },
        { name: "controller_window", type: "string" },
        { name: "controller_alpha_q16", type: "string" },
        { name: "beacon_window_epochs", type: "string" },
      ],
    },
  },
};
